# Site settings
title: My thoughts on Software development
description: "My blog where I share my thoughts on software development"
url: "https://apssouza22.github.io/blog"
author:
  name: "Alexsandro Souza"
  email: "apssouza22@gmail.com"
  url: "https://apssouza22.github.io/blog"

# Build settings
baseurl: /blog/
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
genre: "Science and Technology Blog" # Blog genre
version: "1.0.1"    # Blog site version

# Disqus comments
comments: true      # used to enable disqus comments on site
dsq_shortname: science-blog-template # disqus shortname

# Options: Define which header/footer to use
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
plugins:
  - jekyll-paginate
